packages:
  - apps/*
  - packages/**

catalog:
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@vanilla-extract/css': ^1.18.0
  '@vanilla-extract/recipes': 0.5.7
  '@vanilla-extract/vite-plugin': ^5.1.4
  '@vitejs/plugin-react': ^5.1.1
  eslint: ^9.39.1
  react: ^19.2.0
  react-dom: ^19.2.0
  react-router: ^7.10.1
  typescript: ~5.9.3
  vite: 7.3.0
