packages:
  - apps/*
  - packages/**

catalog:
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.1
  eslint: ^9.39.1
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~5.9.3
  vite: 7.3.0
